/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUIS_Catalogo;

import Controller.AyU.OAyU;
import View.GUIS_AyU.GUILogin;
import View.GUIS_AyU.GUISignUp;
import View.GUIS_AyU.GUI_MiPerfil;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author thann
 */
public class GUI_Catalogo extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Catalogo
     */
    public GUI_Catalogo() {
        initComponents();
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(72, 72, 72));
        resizeImage("/GeekMetrik.png", labelLogo);

        if(GUILogin.autenticado != null) {

            if( GUILogin.autenticado.getTipo() == 1 ) {

                JOptionPane.showMessageDialog(null, "Hola usuario!");

            }

            else {

                JOptionPane.showMessageDialog(null, "Hola admin!");

            }

        }

        else {

            JOptionPane.showMessageDialog(null, "Hola publico en general!");

        }
    }

    public void resizeImage(String foto, JLabel label){
        ImageIcon icon = new ImageIcon( GUI_Catalogo.class.getResource(foto) );
        Image image = icon.getImage();
        Image scale = image.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scale);
        label.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLogo = new javax.swing.JLabel();
        jLabelGEEK = new javax.swing.JLabel();
        jLabelMETRIK = new javax.swing.JLabel();
        jLabelMETRIK2 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonVerVideojuego1 = new javax.swing.JButton();
        labelImagen1 = new javax.swing.JLabel();
        jLabelEstrellas1 = new javax.swing.JLabel();
        jTextFieldTituloVideojuego1 = new javax.swing.JTextField();
        jTextFieldEstr1 = new javax.swing.JTextField();
        jButtonSignUp = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonVerVideojuego2 = new javax.swing.JButton();
        labelImagen2 = new javax.swing.JLabel();
        jLabelEstrellas2 = new javax.swing.JLabel();
        jTextFieldTituloVideojuego2 = new javax.swing.JTextField();
        jTextFieldEstr2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButtonVerVid3 = new javax.swing.JButton();
        labelImagen3 = new javax.swing.JLabel();
        jLabelEstrellas3 = new javax.swing.JLabel();
        jTextFieldTituloVideojuego3 = new javax.swing.JTextField();
        jTextFieldEstr3 = new javax.swing.JTextField();
        jButtonAfter = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonMiPerfil = new javax.swing.JButton();
        jButtonReclamarCode = new javax.swing.JButton();
        jLabelMETRIK3 = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonMoba = new javax.swing.JButton();
        jButtonAccion = new javax.swing.JButton();
        jLabelMETRIK4 = new javax.swing.JLabel();
        jButtonTerror = new javax.swing.JButton();
        jButtonRPG = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelGEEK.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelGEEK.setForeground(new java.awt.Color(104, 164, 255));
        jLabelGEEK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGEEK.setText("Geek");
        jLabelGEEK.setToolTipText("");

        jLabelMETRIK.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelMETRIK.setForeground(new java.awt.Color(186, 126, 255));
        jLabelMETRIK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMETRIK.setText("Metrik");
        jLabelMETRIK.setToolTipText("");

        jLabelMETRIK2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMETRIK2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMETRIK2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelMETRIK2.setText("Catalogo");
        jLabelMETRIK2.setToolTipText("");

        jButtonLogin.setBackground(new java.awt.Color(104, 164, 255));
        jButtonLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("login");
        jButtonLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(91, 91, 91));

        jButtonVerVideojuego1.setBackground(new java.awt.Color(186, 126, 255));
        jButtonVerVideojuego1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonVerVideojuego1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerVideojuego1.setText("Ver Videojuego");
        jButtonVerVideojuego1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButtonVerVideojuego1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerVideojuego1ActionPerformed(evt);
            }
        });

        labelImagen1.setText("Imagen");

        jLabelEstrellas1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEstrellas1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstrellas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstrellas1.setText("Estrellas");
        jLabelEstrellas1.setToolTipText("");

        jTextFieldTituloVideojuego1.setEditable(false);
        jTextFieldTituloVideojuego1.setBackground(new java.awt.Color(91, 91, 91));
        jTextFieldTituloVideojuego1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldTituloVideojuego1.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTituloVideojuego1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldTituloVideojuego1.setText("Titulo 1");
        jTextFieldTituloVideojuego1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldTituloVideojuego1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloVideojuego1ActionPerformed(evt);
            }
        });

        jTextFieldEstr1.setEditable(false);
        jTextFieldEstr1.setBackground(new java.awt.Color(91, 91, 91));
        jTextFieldEstr1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldEstr1.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldEstr1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEstr1.setText("#");
        jTextFieldEstr1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldEstr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstr1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButtonVerVideojuego1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTituloVideojuego1)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEstrellas1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEstr1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelImagen1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextFieldEstr1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEstrellas1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldTituloVideojuego1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVerVideojuego1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButtonSignUp.setBackground(new java.awt.Color(186, 126, 255));
        jButtonSignUp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonSignUp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSignUp.setText("signup");
        jButtonSignUp.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignUpActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(91, 91, 91));

        jButtonVerVideojuego2.setBackground(new java.awt.Color(186, 126, 255));
        jButtonVerVideojuego2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonVerVideojuego2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerVideojuego2.setText("Ver Videojuego");
        jButtonVerVideojuego2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButtonVerVideojuego2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerVideojuego2ActionPerformed(evt);
            }
        });

        labelImagen2.setText("Imagen");

        jLabelEstrellas2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEstrellas2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstrellas2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstrellas2.setText("Estrellas");
        jLabelEstrellas2.setToolTipText("");

        jTextFieldTituloVideojuego2.setEditable(false);
        jTextFieldTituloVideojuego2.setBackground(new java.awt.Color(91, 91, 91));
        jTextFieldTituloVideojuego2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldTituloVideojuego2.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTituloVideojuego2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldTituloVideojuego2.setText("Titulo 1");
        jTextFieldTituloVideojuego2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldTituloVideojuego2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloVideojuego2ActionPerformed(evt);
            }
        });

        jTextFieldEstr2.setEditable(false);
        jTextFieldEstr2.setBackground(new java.awt.Color(91, 91, 91));
        jTextFieldEstr2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldEstr2.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldEstr2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEstr2.setText("#");
        jTextFieldEstr2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldEstr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstr2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTituloVideojuego2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButtonVerVideojuego2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabelEstrellas2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldEstr2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelImagen2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelEstrellas2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTituloVideojuego2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEstr2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVerVideojuego2)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(91, 91, 91));

        jButtonVerVid3.setBackground(new java.awt.Color(186, 126, 255));
        jButtonVerVid3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonVerVid3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerVid3.setText("Ver Videojuego");
        jButtonVerVid3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButtonVerVid3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerVid3ActionPerformed(evt);
            }
        });

        labelImagen3.setText("Imagen");

        jLabelEstrellas3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEstrellas3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstrellas3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstrellas3.setText("Estrellas");
        jLabelEstrellas3.setToolTipText("");

        jTextFieldTituloVideojuego3.setEditable(false);
        jTextFieldTituloVideojuego3.setBackground(new java.awt.Color(91, 91, 91));
        jTextFieldTituloVideojuego3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldTituloVideojuego3.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTituloVideojuego3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldTituloVideojuego3.setText("Titulo 1");
        jTextFieldTituloVideojuego3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldTituloVideojuego3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloVideojuego3ActionPerformed(evt);
            }
        });

        jTextFieldEstr3.setEditable(false);
        jTextFieldEstr3.setBackground(new java.awt.Color(91, 91, 91));
        jTextFieldEstr3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldEstr3.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldEstr3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEstr3.setText("#");
        jTextFieldEstr3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldEstr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstr3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButtonVerVid3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTituloVideojuego3)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEstrellas3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEstr3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelImagen3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextFieldEstr3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEstrellas3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jTextFieldTituloVideojuego3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVerVid3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButtonAfter.setBackground(new java.awt.Color(104, 164, 255));
        jButtonAfter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonAfter.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAfter.setText("<");
        jButtonAfter.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButtonAfter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfterActionPerformed(evt);
            }
        });

        jButtonNext.setBackground(new java.awt.Color(104, 164, 255));
        jButtonNext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonNext.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNext.setText(">");
        jButtonNext.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(91, 91, 91));

        jButtonMiPerfil.setBackground(new java.awt.Color(104, 164, 255));
        jButtonMiPerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonMiPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMiPerfil.setText("Mi Perfil");
        jButtonMiPerfil.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButtonMiPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMiPerfilActionPerformed(evt);
            }
        });

        jButtonReclamarCode.setBackground(new java.awt.Color(104, 164, 255));
        jButtonReclamarCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonReclamarCode.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReclamarCode.setText("Reclamar Codigo");
        jButtonReclamarCode.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButtonReclamarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReclamarCodeActionPerformed(evt);
            }
        });

        jLabelMETRIK3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMETRIK3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMETRIK3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMETRIK3.setText("Geek");
        jLabelMETRIK3.setToolTipText("");

        jButtonLogout.setBackground(new java.awt.Color(104, 164, 255));
        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("logout");
        jButtonLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMETRIK3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMiPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReclamarCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMETRIK3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMiPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReclamarCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(91, 91, 91));

        jButtonMoba.setBackground(new java.awt.Color(186, 126, 255));
        jButtonMoba.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonMoba.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMoba.setText("MOBA");
        jButtonMoba.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButtonMoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMobaActionPerformed(evt);
            }
        });

        jButtonAccion.setBackground(new java.awt.Color(186, 126, 255));
        jButtonAccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonAccion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAccion.setText("Acción");
        jButtonAccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButtonAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccionActionPerformed(evt);
            }
        });

        jLabelMETRIK4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMETRIK4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMETRIK4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMETRIK4.setText("Generos");
        jLabelMETRIK4.setToolTipText("");

        jButtonTerror.setBackground(new java.awt.Color(186, 126, 255));
        jButtonTerror.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonTerror.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTerror.setText("Terror");
        jButtonTerror.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButtonTerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerrorActionPerformed(evt);
            }
        });

        jButtonRPG.setBackground(new java.awt.Color(186, 126, 255));
        jButtonRPG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonRPG.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRPG.setText("RPG");
        jButtonRPG.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButtonRPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRPGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMETRIK4, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jButtonMoba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTerror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRPG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMETRIK4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMoba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTerror)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRPG)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jButtonAfter, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelGEEK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMETRIK)
                        .addGap(7, 7, 7)
                        .addComponent(jLabelMETRIK2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelGEEK, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelMETRIK, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelMETRIK2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonLogin)
                        .addComponent(jButtonSignUp))
                    .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAfter, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        GUILogin gui = new GUILogin();
        OAyU oyente = new OAyU(gui);
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonVerVideojuego1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerVideojuego1ActionPerformed
        // TODO add your handling code here:
        GUI_Mostrar_Videojuego gui = new GUI_Mostrar_Videojuego();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVerVideojuego1ActionPerformed

    private void jButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignUpActionPerformed
        GUISignUp gui = new GUISignUp();
        OAyU oyenteAyU = new OAyU(gui);
        gui.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSignUpActionPerformed

    private void jTextFieldEstr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstr1ActionPerformed

    private void jTextFieldTituloVideojuego1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloVideojuego1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloVideojuego1ActionPerformed

    private void jButtonVerVideojuego2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerVideojuego2ActionPerformed
        // TODO add your handling code here:
        GUI_Mostrar_Videojuego gui = new GUI_Mostrar_Videojuego();
        gui.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonVerVideojuego2ActionPerformed

    private void jTextFieldTituloVideojuego2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloVideojuego2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloVideojuego2ActionPerformed

    private void jTextFieldEstr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstr2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstr2ActionPerformed

    private void jButtonVerVid3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerVid3ActionPerformed
        // TODO add your handling code here:
        GUI_Mostrar_Videojuego gui = new GUI_Mostrar_Videojuego();
        gui.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonVerVid3ActionPerformed

    private void jTextFieldTituloVideojuego3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloVideojuego3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloVideojuego3ActionPerformed

    private void jTextFieldEstr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstr3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstr3ActionPerformed

    private void jButtonAfterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAfterActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonMiPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMiPerfilActionPerformed
        // TODO add your handling code here:
        GUI_MiPerfil gui = new GUI_MiPerfil();
        gui.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonMiPerfilActionPerformed

    private void jButtonReclamarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReclamarCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReclamarCodeActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonMobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMobaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMobaActionPerformed

    private void jButtonAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAccionActionPerformed

    private void jButtonTerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTerrorActionPerformed

    private void jButtonRPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRPGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRPGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAccion;
    public javax.swing.JButton jButtonAfter;
    public javax.swing.JButton jButtonLogin;
    public javax.swing.JButton jButtonLogout;
    public javax.swing.JButton jButtonMiPerfil;
    public javax.swing.JButton jButtonMoba;
    public javax.swing.JButton jButtonNext;
    public javax.swing.JButton jButtonRPG;
    public javax.swing.JButton jButtonReclamarCode;
    public javax.swing.JButton jButtonSignUp;
    public javax.swing.JButton jButtonTerror;
    public javax.swing.JButton jButtonVerVid3;
    public javax.swing.JButton jButtonVerVideojuego1;
    public javax.swing.JButton jButtonVerVideojuego2;
    private javax.swing.JLabel jLabelEstrellas1;
    private javax.swing.JLabel jLabelEstrellas2;
    private javax.swing.JLabel jLabelEstrellas3;
    public javax.swing.JLabel jLabelGEEK;
    public javax.swing.JLabel jLabelMETRIK;
    public javax.swing.JLabel jLabelMETRIK2;
    private javax.swing.JLabel jLabelMETRIK3;
    private javax.swing.JLabel jLabelMETRIK4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JTextField jTextFieldEstr1;
    public javax.swing.JTextField jTextFieldEstr2;
    public javax.swing.JTextField jTextFieldEstr3;
    public javax.swing.JTextField jTextFieldTituloVideojuego1;
    public javax.swing.JTextField jTextFieldTituloVideojuego2;
    public javax.swing.JTextField jTextFieldTituloVideojuego3;
    private javax.swing.JLabel labelImagen1;
    private javax.swing.JLabel labelImagen2;
    private javax.swing.JLabel labelImagen3;
    public javax.swing.JLabel labelLogo;
    // End of variables declaration//GEN-END:variables
}
